name = "Adrenaline"
author = "SkywardMC"
version = "1.23.1+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96f348598a666a42ee3c4f6bc913e4724c990cfb976292a1f30e4b61d5d39e52"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
